resources:
- name: concourse-dockerfile
  type: git
  source:
    uri: git@github.com:jalgraves/concourse_test.git
    branch: master
    private_key: ((github_private_key))
    paths: [Dockerfile]

- name: concourse-build-image
  type: docker-image
  source:
    repository: jalgraves/testing_image
    username: ((dockerhub_user))
    password: ((dockerhub_password))

jobs:
- name: concourse-build-job
  plan:
  - get: concourse-dockerfile
    trigger: true
  - put: concourse-build-image
    params: {build: concourse-dockerfile}
